name: Build GPCS4

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  VULKAN_SDK_VERSION: 1.4.341.1

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.2
      id: vulkan
      with:
        version: ${{ env.VULKAN_SDK_VERSION }}
        cache: true

    - name: Install LLVM
      run: choco install llvm -y

    - name: Setup Developer Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure Paths and LLVM Fix
      shell: pwsh
      run: |
        $llvm_path = "C:\Program Files\LLVM"
        
        $actual_folder = Get-ChildItem -Path "$llvm_path\lib\clang" | 
                         Where-Object { $_.PSIsContainer } | 
                         Select-Object -ExpandProperty Name -First 1
        
        $major_ver = $actual_folder.Split('.')[0]
        Write-Host "Detected LLVM Actual: $actual_folder, Major: $major_ver"

        $link_path = "$llvm_path\lib\clang\$major_ver"
        $target_path = "$llvm_path\lib\clang\$actual_folder"
        
        if ($major_ver -ne $actual_folder) {
            if (-not (Test-Path $link_path)) {
                New-Item -ItemType Junction -Path $link_path -Target $target_path
                Write-Host "Created Junction: $link_path -> $target_path"
            }
        }

        $props = @"
        <Project>
          <PropertyGroup>
            <LLVMInstallDir>$llvm_path</LLVMInstallDir>
            <LLVMToolsVersion>$actual_folder</LLVMToolsVersion>
          </PropertyGroup>
        </Project>
        "@
        Set-Content -Path .\Directory.build.props -Value $props

    - name: Verify Tools
      run: |
        glslc --version
        clang-cl --version

    - name: Build
      shell: cmd
      run: |
        set "VULKAN_ROOT=${{ env.VULKAN_SDK }}"
        set "VULKAN_ROOT=%VULKAN_ROOT:/=\%"

        set "CL=/I"%VULKAN_ROOT%\Include" %CL%"
        set "LINK=/LIBPATH:"%VULKAN_ROOT%\Lib" %LINK%"

        echo --- COMPILER FORCE FLAGS ---
        echo CL: %CL%
        echo LINK: %LINK%
        echo ----------------------------

        msbuild /m ^
          /p:Configuration=Release ^
          /t:Rebuild ^
          /p:LatestTargetPlatformVersion=true ^
          ${{env.SOLUTION_FILE_PATH}}
          
    - name: Setup git hash
      run: |
         for /f "tokens=*" %%i in ('git rev-parse --short HEAD') do set GIT_HASH=%%i
         echo GIT_HASH_SHORT=%GIT_HASH% >> %GITHUB_ENV%
      shell: cmd

    - name: Upload build files
      uses: actions/upload-artifact@v4
      with:
        name: gpcs4-${{ env.GIT_HASH_SHORT }}
        path: |
          x64
          !x64/**/*.pdb
          !x64/**/*.lib
        if-no-files-found: error
